"""add tier_policy ceiling table

Autogenerated against SQLite, so the timestamp defaults came out as SQLite's
CURRENT_TIMESTAMP; rewritten to now() to match every other table in the initial
migration. Production is PostgreSQL (§2), where now() is the convention.

Revision ID: 643ea4b00dfb
Revises: 1e7128bffb7a
Create Date: 2026-09-05 15:45:02.999046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '643ea4b00dfb'
down_revision: Union[str, None] = '1e7128bffb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_policy',
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('ceiling_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier', name='uq_tier_policy_tier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier_policy')
    # ### end Alembic commands ###
