"""customer contact details for the portal profile

Revision ID: d0515684eabe
Revises: 9c4d1a7f52b0
Create Date: 2026-09-05 23:08:47.079961
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0515684eabe'
down_revision: Union[str, None] = '9c4d1a7f52b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('contact_name', sa.String(length=120), nullable=True))
    op.add_column('customer', sa.Column('contact_phone', sa.String(length=40), nullable=True))
    op.add_column('customer', sa.Column('billing_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'billing_address')
    op.drop_column('customer', 'contact_phone')
    op.drop_column('customer', 'contact_name')
    # ### end Alembic commands ###
