"""product unit, tax and description

Revision ID: eb1bb4fe07aa
Revises: d0515684eabe
Create Date: 2026-09-06 04:40:42.205083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb1bb4fe07aa'
down_revision: Union[str, None] = 'd0515684eabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('unit', sa.String(length=30), nullable=False))
    op.add_column('product', sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    op.drop_column('product', 'tax_pct')
    op.drop_column('product', 'unit')
    # ### end Alembic commands ###
